In [8]:
import numpy as np
import pandas as pd
import math

# completematrxi_distance
# [[  0.         148.92279879 254.71650908]
#  [145.34441854  16.2788206  217.86807935]
#  [164.22241016  55.75840744 146.46671977]]
# completematrxi_features
# [[0.04106599 0.67065434 0.71662986]
#  [0.66293585 0.14071851 0.29952253]
#  [0.71140101 0.20902332 0.04381659]]
# distance
# [[0.    0.    0.001]]
# features
# [[0.         0.         0.04106599]
#  [1.         1.         0.14071851]
#  [2.         2.         0.04381659]]


In [40]:
bhattacharya_matrix = np.array( [[0.04106599, 0.67065434, 0.71662986],
                                 [0.66293585, 0.14071851, 0.29952253],
                                 [0.71140101, 0.20902332, 0.04381659]])

bhattacharya_matrix = np.array([[  0.        , 148.92279879, 254.71650908],
                                [145.34441854,  16.2788206 , 217.86807935],
                                [164.22241016,  55.75840744, 146.46671977]])

bhattacharya_matrix[np.where(bhattacharya_matrix  == 0)] = 0.001
bhattacharya_matrix[np.where(bhattacharya_matrix > 140)] = 9999
# get min values in each row
result = np.multiply(bhattacharya_matrix, bhattacharya_matrix == np.min(bhattacharya_matrix, 1)[:, None])

df = pd.DataFrame(result.T)

row_sum = np.sum(df, axis=1)
df1 = df[row_sum != 0].drop_duplicates()
df0 = df[row_sum == 0]

index0 = df0.index.values
index1 = df1.index.values

results = np.arange(0, (np.max(np.hstack([index0, index1]))))
results2 = np.hstack([index0, index1])

remove_objs = np.setdiff1d(results, results2)

result = pd.concat([df1, df0]).sort_index().values.T

# set all the 0 values as 10
result[np.where(result == 0)] = 9999
print(result)
# get min values in each col ( will be less than zero )
result = np.multiply(result, result == np.min(result, 0)[None, :])

print(result)
result[np.where(result == 9999)] = None
result[np.where(result == 0)] = None

pairs = np.argwhere(~np.isnan(result))

pairs_values = result[~np.isnan(result)]
pairs_values = pairs_values[:, np.newaxis]

pairs = np.concatenate((pairs, pairs_values), axis=1)
known_but_not_detected = np.argwhere(np.all(np.isnan(result), axis=0)).flatten()
new_obj = np.argwhere(np.all(np.isnan(result), axis=1)).flatten()

pairs

[[1.00000000e-03 9.99900000e+03 9.99900000e+03]
 [9.99900000e+03 1.62788206e+01 9.99900000e+03]
 [9.99900000e+03 5.57584074e+01 9.99900000e+03]]
[[1.00000000e-03 0.00000000e+00 9.99900000e+03]
 [0.00000000e+00 1.62788206e+01 9.99900000e+03]
 [0.00000000e+00 0.00000000e+00 9.99900000e+03]]


array([[0.00000000e+00, 0.00000000e+00, 1.00000000e-03],
       [1.00000000e+00, 1.00000000e+00, 1.62788206e+01]])

In [62]:
a = np.array([[0.        , 0.        , 0.04106599],
       [1.        , 1.        , 0.14071851],
       [2.        , 2.        , 0.04381659]])

b = np.array([[0.00000000e+00, 0.00000000e+00, 1.00000000e-03],
       [1.00000000e+00, 1.00000000e+00, 1.62788206e+01]])

if a.shape[0] > b.shape[0]:
    arr_A = a
    arr_B = b
else:
    arr_B = a
    arr_A = b

final_array = np.empty((0,4))
for idx, row in enumerate(arr_B[:,0:2]):
    final_array = np.vstack((final_array,np.array([arr_A[idx,0], arr_A[idx,1], arr_A[idx,2], arr_B[idx,2]])))

print(final_array)



    def distance_calc(self, x1, y1, x2, y2):
        return math.sqrt(((x2 - x1) ** 2) + ((y2 - y1) ** 2))



[[0.00000000e+00 0.00000000e+00 4.10659900e-02 1.00000000e-03]
 [1.00000000e+00 1.00000000e+00 1.40718510e-01 1.62788206e+01]]


In [63]:
# 493.0 464.0
# 650.0 283.5
# 653.0 285.0
# 653.5 289.0
# 653.5 287.5

def distance_calc(x1,y1,x2,y2):
    return math.sqrt(((x2 - x1) ** 2) +  ((y2 - y1) ** 2))

print(distance_calc(493,464,650,283))
print(distance_calc(650,283,653,285))
print(distance_calc(653,285,653.5,289))
print(distance_calc(653.5,289,653.5,287.5))

239.60383970212163
3.605551275463989
4.031128874149275
1.5
